export const START_MOVE_DRAUGHT = 'tile/START_MOVE_DRAUGHT'

export const HIGHLIGHT_NEIGHBOUR_TILES = 'tile/HIGHLIGHT_NEIGHBOUR_TILES'

export const REMOVE_DRAUGHT = 'tile/REMOVE_DRAUGHT'

export const ADD_DRAUGHT = 'tile/ADD_DRAUGHT'

export const UPDATE_BOARD = 'tile/UPDATE_BOARD'
