export const START_MOVE_DRAUGHT = 'tile/START_MOVE_DRAUGHT'

export const MOVE_DRAUGHT = 'tile/MOVE_DRAUGHT'

export const HIGHLIGHT_NEIGHBOUR_TILES = 'tile/HIGHLIGHT_NEIGHBOUR_TILES'

export const REMOVE_DRAUGHT = 'tile/REMOVE_DRAUGHT'
