export const SELECT_DRAUGHT = 'SELECT_DRAUGHT'

export const SELECT_DRAUGHT_SYNC = 'SELECT_DRAUGHT_SYNC'

export const MOVE_DRAUGHT = 'MOVE_DRAUGHT'

export const MOVE_DRAUGHT_SYNC = 'MOVE_DRAUGHT_SYNC'
