export const SELECT_DRAUGHT = 'SELECT_DRAUGHT'

export const SELECT_DRAUGHT_SYNC = 'SELECT_DRAUGHT_SYNC'

export const HIGHLIGHT_TILE = "HIGHLIGHT_TILE"

export const REMOVE_DRAUGHT = "REMOVE_DRAUGHT"

export const MOVE_DRAUGHT = 'MOVE_DRAUGHT'

export const MOVE_DRAUGHT_SYNC = 'MOVE_DRAUGHT_SYNC'
