export const START_SELECT_DRAUGHT = 'START_SELECT_DRAUGHT'

export const SELECT_DRAUGHT = 'SELECT_DRAUGHT'

export const HIGHLIGHT_TILE = "HIGHLIGHT_TILE"

export const REMOVE_DRAUGHT = "REMOVE_DRAUGHT"

export const START_MOVE_DRAUGHT = 'START_MOVE_DRAUGHT'

export const MOVE_DRAUGHT = 'MOVE_DRAUGHT'
